version: 2

build:
    os: "ubuntu-20.04"
    tools:
        python: "3.8"
    apt_packages:
        - libsnmp-dev
        - snmp-mibs-downloader

sphinx:
    fail_on_warning: true

formats:
    - pdf
    - epub

python:
    install:
        - method: pip
          path: .
        - requirements: requirements.txt
